version: '3.5'
services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    networks:
      - semapps
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=simon.louvet.pro@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  fuseki_compact:
    image: semapps/jena-fuseki-webacl:latest
    entrypoint: /docker-compact-entrypoint.sh
    image: semapps/jena-fuseki-webacl
    volumes:
      - ./data/fuseki:/fuseki

  fuseki:
    image: semapps/jena-fuseki-webacl:latest
    container_name: fuseki
    restart: on-failure
    depends_on:
      - "fuseki_compact"
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: middleware
    restart: on-failure
    depends_on:
      - "traefik"
    volumes:
      - ./server/:/app
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "yarn install &&  pm2-runtime 'yarn run dev'"
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_HOME_URL=https://data.resilience.data-players.com/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware.rule=Host(`data.resilience.data-players.com`)"
      - "traefik.http.routers.middleware.entrypoints=websecure"
      - "traefik.http.routers.middleware.tls.certresolver=myresolver"
networks:
  semapps:
    name: semapps_network
