version: '3.5'
services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik-coographie"
    networks:
      - semapps
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  fuseki:
    image: stain/jena-fuseki:3.10.0
    container_name: fuseki-coographie
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: middleware-coographie
    depends_on:
      - fuseki
    volumes:
      - ./server/:/app
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "npm install && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware.rule=Host(`middleware.localhost`)"
      - "traefik.http.routers.middleware.entrypoints=web"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: frontend-coographie
    environment:
      - PORT=5000
    volumes:
      - ./client:/app
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: bash -c "npm rebuild && npm install --silent && npm run bootstrap && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"

networks:
  semapps:
    name: semapps_network
