version: '3.5'

services:
  fuseki:
    image: stain/jena-fuseki:3.10.0
    container_name: fuseki-coographie
    restart: always
    volumes:
      - ../data/fuseki:/fuseki
      - ../data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: semapps-coographie
    restart: always
    depends_on:
      - fuseki
    volumes:
      - ./:/app
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "npm install && npm start"



volumes:
  rdf_data:
  staging:
networks:
  semapps:
    name: semapps_network
